# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'StudentLink' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudentLink

    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod ‘SwiftyJSON’

  target 'StudentLinkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
